repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        files: "\\.(py)$"
        args: [--sp=pyproject.toml ]
  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
      - id: black
        files: "\\.(py)$"
        language_version: python3.10
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [Flake8-pyproject]
        files: "\\.(py)$"
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.19.13
    hooks:
      - id: djlint-handlebars
        files: "\\.html"
        types_or: ['html']
