# Generated by Django 4.1.9 on 2023-05-20 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import repositories.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentsCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("document", models.FileField(upload_to="cache/%Y/%m/%d")),
            ],
            options={
                "verbose_name": "Cache Document",
                "verbose_name_plural": "Cache Documents",
            },
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250, verbose_name="Название")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Repository",
                "verbose_name_plural": "Repositories",
            },
        ),
        migrations.CreateModel(
            name="RepositoryMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "repository",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="repositories.repository"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Repository member",
                "verbose_name_plural": "Repository members",
            },
        ),
        migrations.AddField(
            model_name="repository",
            name="repository_members",
            field=models.ManyToManyField(
                related_name="repositories",
                through="repositories.RepositoryMember",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Участники",
            ),
        ),
        migrations.CreateModel(
            name="Commit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.CharField(max_length=100)),
                ("changes", models.TextField(validators=[repositories.utils.validate_xml])),
                ("document", models.FileField(upload_to="documents/%Y/%m/%d")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="commits", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="repositories.repository",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commit",
                "verbose_name_plural": "Commits",
                "ordering": ["-created_at"],
            },
        ),
    ]
