version: '3.9'

volumes:
  psql_data:
    driver: local
  rabbit_data:
    driver: local

x-service-backend:
  &x-service-backend
  build:
    context: ../../
    dockerfile: ci/dev/docker/backend/Dockerfile
  volumes:
    - "../../src/:/var/app/src"
  environment:
    DJANGO__SECRET_KEY: ${DJANGO__SECRET_KEY}
    DJANGO__DEBUG: ${DJANGO__DEBUG}

    DSN__DATABASE: 'postgres://diploma:diploma@postgres:5432/diploma'
    DSN__RABBITMQ: 'amqp://diploma:diploma@rabbit:5672/diploma'

services:
  backend:
    <<: *x-service-backend
    expose:
      - 8000
    restart: on-failure
    depends_on:
      - postgres

  celery:
    <<: *x-service-backend
    depends_on:
      - backend
      - rabbit
    restart: always
    command:
      [
        'celery',
        '--app',
        'config',
        'worker',
        '-l',
        'INFO',
        '--pool=solo'
      ]

  celery-beat:
    <<: *x-service-backend
    depends_on:
      - celery
    restart: always
    command: [ 'celery', '-A', 'config', 'beat', '-l', 'INFO' ]

  postgres:
    image: postgres:15-alpine
    restart: always
    expose:
      - 5432
    volumes:
      - "psql_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: 'diploma'
      POSTGRES_PASSWORD: 'diploma'
      POSTGRES_DB: 'diploma'
      POSTGRES_INITDB_ARGS: "--auth-local=md5"

  rabbit:
    image: "rabbitmq:3.10-management-alpine"
    hostname: 'rabbit'
    environment:
      RABBITMQ_DEFAULT_USER: 'diploma'
      RABBITMQ_DEFAULT_PASS: 'diploma'
      RABBITMQ_DEFAULT_VHOST: 'diploma'
    volumes:
      - "rabbit_data:/var/lib/rabbitmq/"
    expose:
      - 5672
      - 15672
    restart: always
